export const documentRequest = {
  administratifs: [
    'Formulaire de demande de visa',
    'Passeport valide',
    'Photocopies du passeport',
    'Carte nationale d’identité',
    'Photographies d’identité',
    'Acte de naissance',
    'Acte de mariage',
    'Acte de divorce',
    'Livret de famille',
    'Autorisation parentale pour mineur',
  ],
  financiers: [
    'Preuve de paiement des frais de visa',
    'Relevés bancaires (3 à 6 derniers mois)',
    'Attestation de prise en charge / Lettre de sponsor',
    'Bulletins de salaire',
    'Attestation de travail',
    'Contrat de travail',
    'Déclaration d’impôts / Avis d’imposition',
    'Justificatifs de biens',
  ],
  voyage: [
    'Réservation d’hôtel ou attestation d’hébergement',
    'Lettre d’invitation',
    'Billet d’avion (aller-retour ou réservation)',
    'Assurance voyage',
    'Itinéraire de voyage détaillé',
  ],
  académiques_professionnels: [
    'Lettre de motivation',
    'Lettre d’admission (études)',
    'Preuve de paiement des frais de scolarité',
    'Diplômes / certificats / relevés de notes',
    'Lettre d’invitation d’une entreprise',
    'Preuve d’inscription à un congrès',
  ],
  médicaux_judiciaires: [
    'Certificat médical',
    'Carnet de vaccination',
    'Casier judiciaire récent',
    'Test de dépistage (VIH, tuberculose, COVID)',
  ],
  autres: [
    'Lettre d’engagement de retour au pays',
    'Attestation d’employeur de congé',
    'Certificat de scolarité (mineur)',
    'Preuve de ressources du garant',
    'Autorisation de sortie du territoire',
    'Lettre explicative (ex: changement de passeport)',
  ],
}
